{% set name = "psycopg2cffi" %}
{% set version = "2.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # sha256: bb8577f22f92cab13a760c1087a79c7eaf543b6ea2b1fe77c7c778976d0cc333
  # execute `conda build .` in the 
  path: ./

build:
  noarch: python
  number: 0
  skip: True  # [py<35]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - pip
    - cffi
  run:
    - python

about:
  home: https://github.com/trumanw/psycopg2cffi
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'An implementation of the psycopg2 module using cffi. The module is currently compatible with Psycopg 2.5.'
  description: |
    An implementation of the psycopg2 module using cffi. The module is currently compatible with Psycopg 2.5.
  doc_url: https://github.com/trumanw/psycopg2cffi
  dev_url: https://github.com/trumanw/psycopg2cffi
